### ISSUE TITLE
About using hybrid task for run_cifar10.sh

### ISSUE THREAD

**Issue by musikisomorphie** [thu-ml/implicit-normalizing-flows#1]
Hi @LuChengTHU, thank you for the great work, which is very inspiring. 
I run your code by defaulting settings, which work very well.
Now, I wanted to train your model for the hybrid task. Specifically, I run 
run_cifar10.sh with adding --task hybrid, then I got the following error

> Traceback (most recent call last):
>   File "train_img.py", line 507, in <module>
>     model(x, restore=True)
>   File "/home/miniconda3/envs/research/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/GitHub/implicit-normalizing-flows/lib/implicit_flow.py", line 198, in forward
>     x = self.transforms[idx].forward(x, restore=restore)
>   File "/home/GitHub/implicit-normalizing-flows/lib/layers/container.py", line 15, in forward
>     x = self.chain[i](x, restore=restore)
>   File "/home/miniconda3/envs/research/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
> TypeError: forward() got an unexpected keyword argument 'restore'

Can someone help me with the error? Thank you very much.

**Comment by LuChengTHU** [comment]
Hi @musikisomorphie , thanks for your interest in our work!

We didn't run the hybrid modeling task in our experiments. Our code is based on the released code of 'Residual Flows' and we didn't remove the unused parts.

Nevertheless, you can try to train the tasks to check the performance. The error above is because we need to add a new keyword "restore" for the "forward" function to all flow blocks in "self.trainsforms". You can check "self.transforms" to see what transforms are used and modify them. In our experiments we only modify the transforms that we needed.

**Comment by musikisomorphie** [comment]
Thank you for the reply, @LuChengTHU. 
Problem solved, just added the restore parameter in Normalize class implemented in the elemwise.py.
@LuChengTHU, you could also update your code if you like, one parameter can do the job.
